platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos7-test
    tag: gpdb7-latest
    username:
    password:
inputs:
  - name: gpdb_src
run:
  path: gpdb_src/concourse/scripts/unit_tests_gpcloud.bash
